

name: Build Kernel

on:
  push:
    paths:
      - '.github/workflows/build-kernel.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: /usr/local/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu
          key: gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu

      - name: Install toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/aarch64-linux-gnu/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz
          sudo tar xvf gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz  -C /usr/local/
      - name: Build kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=/usr/local/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-
          make rockchip_linux_defconfig
          make -j8
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: rockchip-kernel
          path: |
            **
          if-no-files-found: ignore
